### ISSUE TITLE
Type bug

### ISSUE THREAD

**Issue by rufat** [KnorpelSenf/typegram#44] opened 2023-02-02 18:24 UTC
Hi. I'm having this issue when I compile. I'm using:  "telegraf": "^4.11.2".

```
node_modules/telegraf/typings/composer.d.ts:7:15 - error TS1005: ',' expected.

7 import { type CallbackQuery } from './core/types/typegram';
                ~~~~~~~~~~~~~

node_modules/typegram/index.d.ts:10:15 - error TS1005: ',' expected.

10 export { type Typegram } from "./proxied";
                 ~~~~~~~~
```

**Comment by KnorpelSenf** [comment] 2023-02-02 19:59
Most likely, you're using an ancient TypeScript version. Which one is it?

**Comment by itxve** [comment] 2023-02-07 12:29
"typescript": "^4.9.5"
same‘s issue

**Comment by KnorpelSenf** [comment] 2023-02-07 14:30
Does it happen with typegram 4.1.0 already? If not, then I know the problem

**Comment by KnorpelSenf** [comment] 2023-02-07 20:47
@rufat @itxve can you check if #45 fixes the problem and approve the pull request?

**Comment by rufat** [comment] 2023-02-07 22:53
> @rufat @itxve can you check if #45 fixes the problem and approve the pull request?

This time I only got this:
```
node_modules/telegraf/typings/composer.d.ts:7:15 - error TS1005: ',' expected.

7 import { type CallbackQuery } from './core/types/typegram';
```

I'm using "typescript": 4.3.5. I will upgrade. Meanwhile, @itxve or @KnorpelSenf could you please test it on your side?

**Comment by KnorpelSenf** [comment] 2023-02-07 22:57
That error isn't related to typegram anymore, even though it may seem like that because it's importing from typegram.

I'll wait for another confirmation, though.

**Comment by itxve** [comment] 2023-02-09 03:26
> > @rufat @itxve can you check if #45 fixes the problem and approve the pull request?
> 
> This time I only got this:
> 
> ```
> node_modules/telegraf/typings/composer.d.ts:7:15 - error TS1005: ',' expected.
> 
> 7 import { type CallbackQuery } from './core/types/typegram';
> ```
> 
> I'm using "typescript": 4.3.5. I will upgrade. Meanwhile, @itxve or @KnorpelSenf could you please test it on your side?

I am got a same‘s issue, wait for another confirmation, though


> @rufat @itxve

#45 it's ok, but I got the same problem with @rufat , that is `telegraf` issue.

**Comment by KnorpelSenf** [comment] 2023-02-09 09:36
That's surprising. @MKRhere do you have any clue why type imports don't parse? I know they aren't supported in `.d.ts` files—but that doesn't explain the above error.

**Comment by MKRhere** [comment] 2023-02-09 09:54
```
typescript@4.9.5
telegraf@4.11.2
typegram@4.2.0
```

`"skipLibCheck": false` in tsconfig.json

```sh
$ npm run prepare
> telegraf-bot@1.0.0 prepare
> tsc
$ 
```

No errors here. Anything I should change to reproduce this error?

> I know they aren't supported in `.d.ts` files

Source? The `.d.ts` in question was built by TypeScript. If it's not supported, that would mean a compiler bug.
Regardless, using type imports in a new file seems to work just fine.

**Comment by KnorpelSenf** [comment] 2023-02-09 10:07
I have no idea how to reproduce it.

> Source? The `.d.ts` in question was built by TypeScript. If it's not supported, that would mean a compiler bug.

I remember this being the case long ago. If it is supported now, then it seems like #45 can be closed without merging. The problem seems to be somewhere else.

**Comment by MKRhere** [comment] 2023-02-09 10:11
@rufat @itxve Could you share a small repro or tell us what to change to get the error? I tried with a default tsconfig (`tsc --init`) with only `skipLibCheck` set to false. I can't work out why it'd parse error.

**Comment by itxve** [comment] 2023-02-13 05:22
> @rufat @itxve Could you share a small repro or tell us what to change to get the error? I tried with a default tsconfig (`tsc --init`) with only `skipLibCheck` set to false. I can't work out why it'd parse error.
Sorry to reply to you now，This my repo `https://github.com/itxve/telegram-vercel`
node :`v16.14.2`

**Comment by MKRhere** [comment] 2023-02-13 05:38
@itxve I cloned this, ran `npm install` and `npm run build`:

```TS
 $ npm run build

> telegram-vercel@1.0.0 build
> tsc --noEmit && vite build

vite v4.1.1 building for production...
✓ 1 modules transformed.
Generated an empty chunk: "index".
dist/index.html  0.00 kB
```

This is not what you see?

**Comment by itxve** [comment] 2023-02-13 06:15
> 



> @itxve I cloned this, ran `npm install` and `npm run build`:
> 
> ```ts
>  $ npm run build
> 
> > telegram-vercel@1.0.0 build
> > tsc --noEmit && vite build
> 
> vite v4.1.1 building for production...
> ✓ 1 modules transformed.
> Generated an empty chunk: "index".
> dist/index.html  0.00 kB
> ```
> 
> This is not what you see?
I found that it might be caused by`vercel`,I am not use `vercel` it ok。

**Comment by itxve** [comment] 2023-02-13 06:59
> @itxve I cloned this, ran `npm install` and `npm run build`:
> 
> ```ts
>  $ npm run build
> 
> > telegram-vercel@1.0.0 build
> > tsc --noEmit && vite build
> 
> vite v4.1.1 building for production...
> ✓ 1 modules transformed.
> Generated an empty chunk: "index".
> dist/index.html  0.00 kB
> ```
> 
> This is not what you see?

`export type {  Typegram } from "./proxied";` vs `export  { type Typegram } from "./proxied";` different.
`export type {  Typegram } from "./proxied`  has not compiler error.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/33005087/218394659-2027063f-824b-42ce-a295-46a7596bbaad.png">

**Comment by KnorpelSenf** [comment] 2023-02-13 08:21
Everything about this error tells me that you're using an old version of TypeScript. Is there any way this is possible?

Consider replacing the build command which invokes `tsc` with `tsc --version`.

**Comment by itxve** [comment] 2023-02-13 08:55
> Everything about this error tells me that you're using an old version of TypeScript. Is there any way this is possible?
> 
> Consider replacing the build command which invokes `tsc` with `tsc --version`.
my `tsc ` version
<img width="476" alt="image" src="https://user-images.githubusercontent.com/33005087/218413126-8ea7ef20-5cc7-4731-a4bb-41fe8eb5438a.png">

**Comment by itxve** [comment] 2023-02-13 09:36
This problem only occurs when I use `vercel` for local development. It is not reported at compile time, but only at runtime. This may be a problem with `vercel`. Let's close this problem.

**Comment by MKRhere** [comment] 2023-02-13 10:20
Thanks for confirming this; your version of `vercel` and hence its version of tsc may be old as well; consider upgrading vercel to latest.

**Closed as completed** 2023-02-13 10:39 UTC
